<div id="DIAnetContainerHeader">
    <table width="100%">
        <tr>
            <td width="150" align="center" valign="top"><img height="75"
                                                             src="imagenes/logo_Cliente.png" />
            </td>
            <td align="center"><div style="color: #FFFFFF; font-size: 24px;">WEB-MHTW</div></td>
            <td width="150" align="center">
            </td>
        </tr>
    </table>
</div>