
<%
response.setHeader("Cache-Control","no-cache");
response.setHeader("Cache-Control","no-store");
response.setHeader("Pragma","no-cache"); 
response.setDateHeader ("Expires", -1);
%>

<link rel="stylesheet" href="css/dianet-styles-SGT.css" media="screen" />
<link rel="stylesheet" href="css/global.css" media="screen" />
<link rel="stylesheet" href="css/CalendarPopup.css" media="screen" />

<script type="text/javascript" src="javascript/table.js"></script>
<script type="text/javascript" src="javascript/CalendarPopup.js"></script>
<script type="text/javascript" src="javascript/date.js"></script>

<script type="text/javascript" src="javascript/mweb.js"></script>
<script type="text/javascript" src="javascript/entradas.js"></script>
<script type="text/javascript" src="javascript/entregas.js"></script>
<script type="text/javascript" src="javascript/stocks.js"></script>
